### PR TITLE
Editing Css

### PR DESCRIPTION
**Pull request by AmanWorku**
- Edited the css

### CODE REVIEW

**Review by AmanWorku — COMMENTED** [review]
STATUS: REQUIRED CHANGES ♻️
Hi [@AmanWorku](https://github.com/AmanWorku) 👋
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍
unnamed

Required Changes:
- Please configure your linters. Because you need your code to be clean and crisp so that it can be readable and maintainable by others.
- Please use <section> tag to contain your major sections in your code as it will be helpful to understand where the specific sections go.
- For a more professionally-looking repo, I would suggest using a more descriptive name for your branches. In this way, you can ensure that anyone who accesses your code base can easily get around it and have an idea of what is being developed in that branch 💡 😉 . For example, in this case, you could use a name like header-section or any other alternative you might come up with that will briefly describe the feature👍.

Optional suggestions ☑️

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code 💯

- Creating a professional looking README.md file will help you have great overview of your repo or project for others.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Happy coding and keep it up! 🙌

**Review by jerryowusu — CHANGES_REQUESTED** [review]
Hi @AmanWorku 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are some few changes to make your project look professional :sunglasses:

almost-paul-walker

## Highlights
:heavy_check_mark: utilized the "Review changes" feature from GitHub.
:heavy_check_mark: Added more than two review comments

## Required Changes ♻️

- [ ] Kindly use the [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) at least once to leave review comments. Also, make sure you leave the comment under a line or block of code that fits the context the comment is about.You should use this at least once to leave review comments.

Make sure the student left the comment under a line or block of code that fits the context the comment is about.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by AmanWorku — COMMENTED** [review]
STATUS: REQUIRED CHANGES ♻️
Hi [@AmanWorku](https://github.com/AmanWorku) 👋
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍
unnamed
Required Changes:

Please configure your linters. Because you need your code to be clean and crisp so that it can be readable and maintainable by others.
Please use
tag to contain your major sections in your code as it will be helpful to understand where the specific sections go.
For a more professionally-looking repo, I would suggest using a more descriptive name for your branches. In this way, you can ensure that anyone who accesses your code base can easily get around it and have an idea of what is being developed in that branch 💡 😉 . For example, in this case, you could use a name like header-section or any other alternative you might come up with that will briefly describe the feature👍.
Optional suggestions ☑️

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code 💯

Creating a professional looking README.md file will help you have great overview of your repo or project for others.
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Happy coding and keep it up! 🙌

**Review by Alfredbis29 — APPROVED** [review]
# STATUS: APPROVED  
 Hi @felixDev22   :tada:  !
 
You have successfully completed this project! There is nothing else to say other than... it's time to merge it! rocket Time to celebrate, you have done a fantastic job, congratulations! :tada:

  
 ##  Highlights 
- Used GitHub's 'Review changes' feature from GitHub :heavy_check_mark: 
- Wrote at least 2 comments in the review :heavy_check_mark:  
- Utilised GitHub's inline comments feature for reviews :heavy_check_mark: 

 APPROVED! :100: :100: :100:

## Optional suggestions 
 _Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code 100_
 
 * [ ]  **[OPTIONAL]:

- [ ] You can use a couple of emojis and/or gifs to make the review more human-friendly. I can see you tried to add a few of them but they are not working. Kindly check and make sure they are. :upside_down_face:  :wink: 
- [ ] Check below the review :wink: 

Cheers and best of luck with the following projects! :raised_hands:
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me **@alfredbis29** in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmanWorku** [comment]
Thank you so much it helped a lot.

**Pull request merged**
